In [13]:
import gymnasium as gym
import numpy as np
from gymnasium import spaces

# Spaces

### Box

In [17]:
space_example_1 = spaces.Box(low=0, high=1,shape=(5,), dtype=float)
for i in range(10): print(space_example_1.sample())
space_example_2 = spaces.Box(low=0, high=1, shape=(2,2),dtype=int)
for i in range(10): print(space_example_2.sample())
space_example_3 = spaces.Box(low=np.array([0, 0, 0]), high=np.array([1, 10, 100]), dtype=float)
for i in range(10): print(space_example_3.sample())

[0.23681181 0.77411588 0.16444832 0.66284191 0.14854253]
[0.01313294 0.41613244 0.0835804  0.64499292 0.69794299]
[0.43445887 0.14970431 0.99882417 0.09403666 0.77609758]
[0.41500458 0.64744455 0.33877238 0.86146333 0.36596008]
[0.5091448  0.8957951  0.58999932 0.92313119 0.09726795]
[0.87461336 0.85390712 0.317921   0.23549923 0.10489808]
[0.64084816 0.52804331 0.07290601 0.93285498 0.89479087]
[0.05914622 0.82047362 0.73078881 0.35730134 0.70120528]
[0.92904035 0.83333355 0.16911232 0.98786701 0.14033344]
[0.22076206 0.86139928 0.65514576 0.20108933 0.94667719]
[[0 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 1]
 [1 0]]
[[0 1]
 [0 1]]
[[1 0]
 [1 1]]
[[0 1]
 [0 0]]
[[0 1]
 [1 0]]
[[0 0]
 [1 1]]
[[1 0]
 [1 0]]
[[1 1]
 [1 0]]
[0.43050552 1.86433642 9.69810914]
[ 0.92536919  3.70379717 29.00179875]
[ 0.6320494   2.3807592  57.79846472]
[ 0.52399639  3.74994128 91.96521832]
[ 0.5207306   6.35069778 76.79566153]
[ 0.55343787  6.56688527 28.60107371]
[ 0.93579402  3.55501197 95.99578886]
[ 0.42151296  5.7

### Discrete

In [21]:
space_example_4 = spaces.Discrete(3, start=1)
for i in range(10): print(space_example_4.sample())

1
1
2
1
1
1
3
1
3
3


### Text

In [24]:
space_example_5 = spaces.Text(max_length=5, min_length=5, charset=frozenset({'1', '2', '3', '4', '5', '6'}))
for i in range(10): print(space_example_5.sample())

12126
42236
15666
64261
35364
32242
21314
54623
56666
32236


### Dict

In [31]:
space_example_6_dict = {
    "turnNumber": spaces.Discrete(14*4,start=1),
    "rollNumber": spaces.Discrete(3,start=1),
    "grid": spaces.Box(low=-145, high=145, shape=(14, 4)),
    "announced": spaces.Discrete(2,start=0),
    "announcedRow": spaces.Discrete(14, start=0),
    "roll": spaces.Box(low=0, high=5, shape=(5,), dtype=int),
}
space_example_6 = spaces.Dict(space_example_6_dict)
space_example_6.sample()

OrderedDict([('announced', 1),
             ('announcedRow', 7),
             ('grid',
              array([[ 104.70917  ,   38.54352  ,   51.353348 ,  133.81113  ],
                     [ 101.35764  ,   52.245953 ,   53.330654 ,   -5.550946 ],
                     [ -49.27987  ,   87.63225  ,  130.65039  ,   -7.629896 ],
                     [ -22.104834 ,  -58.561176 ,   86.591995 ,  -47.63159  ],
                     [  -9.571638 ,  -38.66847  , -105.88202  ,  -56.2279   ],
                     [ 144.76065  ,   45.90629  ,  -61.418316 ,   16.606709 ],
                     [  87.826225 ,  -13.487684 ,   71.00311  ,  -28.565    ],
                     [  -5.9770036, -125.69221  ,   94.95585  ,  130.47585  ],
                     [ -50.009666 ,  -44.082966 ,   27.45699  ,   67.92927  ],
                     [ 140.44104  ,  -26.877453 ,  128.61024  ,  135.63574  ],
                     [ -89.95627  ,   58.626743 ,   99.76696  ,  142.4522   ],
                     [  89.10511  ,   43.607